### ISSUE TITLE
Question about HttpRequestData

### ISSUE THREAD

**Issue by alexanderbikk** [jeffhollan/functions-net5-entityframework#1]
Hi @jeffhollan
Thanks for the good test project :)

I have a question did you have [this issue ](https://github.com/Azure/azure-functions-dotnet-worker-preview/issues/51) with HttpRequestData?

**Comment by jeffhollan** [comment]
I did but it was resolved with preview4 of worker. I don’t see that on nuget though. Let me escalate

**Comment by alexanderbikk** [comment]
I also thought that it was fixed in preview4  since I see that you are already used it in your project. But as you can see the preview4   version is not available in NuGet.

Thanks in advance @jeffhollan  :)
